Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/GameObject.prefab
Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/GameObject.prefab.meta
Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/Minimap (New).prefab
Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/Minimap (New).prefab.meta
Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/Minimap.prefab
Frontend/VIAProMa/Assets/Scenes/MinimapTestScene.unity
Frontend/VIAProMa/Assets/Scripts/ScriptableObjects/Multiplayer/Resources/NetworkPrefabs.asset
Frontend/VIAProMa/Assets/Scripts/Visualizations/Kanban Board/KanbanBoardColumnVisualController.cs
Frontend/VIAProMa/Assets/Scripts/Visualizations/Minimap/Minimap.cs
Frontend/VIAProMa/Assets/Scripts/Visualizations/Minimap/MinimapConfiguration.cs
Frontend/VIAProMa/Assets/Scripts/Visualizations/Minimap/MinimapController.cs
Frontend/VIAProMa/Assets/Scripts/Visualizations/Minimap/MinimapHandle.cs
Frontend/VIAProMa/Assets/Tests/Visualizations/Minimap.meta

Basic functionality for the minimap surface

Merge Feature/minimap positioning into World-in-a-miniature

---

Frontend/VIAProMa/Assets/Prefabs/MockupEditor/Description.prefab
Frontend/VIAProMa/Assets/Prefabs/MockupEditor/MockUpWindow.prefab
Frontend/VIAProMa/Assets/Scripts/Mockup Editor/OpenMockUp.cs

Added the function to automatically close description window when closing mockup editor

Added automatic close

---

Frontend/VIAProMa/Assets/Prefabs/MockupEditor/Description.prefab
Frontend/VIAProMa/Assets/Prefabs/MockupEditor/MockUpWindow.prefab
Frontend/VIAProMa/Assets/Scripts/Mockup Editor/OpenMockUp.cs
Frontend/VIAProMa/ProjectSettings/TagManager.asset

Moved description window a little bit to the right.
Dragged window will always face to the user.
Description window is now draggable.
Following window will always be orthognal to the ground
Co-Authored-By: NoraHis <44969350+NoraHis@users.noreply.github.com>

Position fine tuning

---

Frontend/VIAProMa/Assets/Prefabs/UI/Main Menu.prefab
Frontend/VIAProMa/Assets/Scenes/MainScene.unity
Frontend/VIAProMa/Assets/Scripts/UI/Main Menu Cube/FoldController.cs
Frontend/VIAProMa/Assets/Scripts/UI/Main Menu Cube/MainMenu.cs

The menu now doesn't fold anymore, when a button is clicked. Instead, it folds automatically when it is not used for two minutes. The time after it is closes and if it should be closed at all can be configured in the editor on the FoldController Component:
I also repositioned the server status menu sligthly to the left, since it was clipping into the now unfolded menu.
Closes #283

Do not fold menu cube when clicking a button on it

---

Frontend/VIAProMa/Assets/GuidedTour/Configuration.meta
Frontend/VIAProMa/Assets/GuidedTour/Configuration/GuidedTour.json
Frontend/VIAProMa/Assets/GuidedTour/Configuration/GuidedTour.json.meta
Frontend/VIAProMa/Assets/GuidedTour/Scenes/GuidedTourScene.unity
Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration.meta
Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/ConfigFile.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/ConfigFile.cs.meta
Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/ConfigFileTypes.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/ConfigFileTypes.cs.meta
Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourManager.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourUtils.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourUtils.cs.meta
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/AbstractTourTask.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/SimpleTourTask.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/TourSection.cs

Closes #300, #301, #302 and #303.
I also placed to SimpleTourTasks with identifiers in the scene to give example on how to place tasks and use the identifers in the configuration file. These tasks ("Task 1" and "Task 2") can be deleted as the real tasks are introduced.
After review the GuidedTour/backend branch can be deleted.

Completed backend work for Guided Tour

---

Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTaskEventHandler.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTourTask.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTaskEventHandler.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTourTask.cs

Close #294
#295 need to fix the SkipTask Method.

Closes #294 and #295 is still work-in-progress

---

Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GuidedTourWidget.prefab
Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GuidedTourWidget.prefab.meta
Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourWidget.cs

Finished working on #296 and #297. Widget will now be a single widget that will be updated and  not an instance for every task.

Guided tour/visual components

---

Frontend/VIAProMa/Assets/MRTK/Core/Utilities/WebRequestRest.meta
Frontend/VIAProMa/Assets/Scenes/MainScene.unity
Frontend/VIAProMa/Assets/Scripts/DeepLinks/DeepLinkBootstrapper.cs
Frontend/VIAProMa/Assets/Scripts/DeepLinks/DeepLinkBootstrapper.cs.meta
Frontend/VIAProMa/Assets/Scripts/DeepLinks/DeepLinkManager.cs
Frontend/VIAProMa/ProjectSettings/QualitySettings.asset

Bootstrapper reacts to DeepLinks.

DeepLinks | DeepLinkBootstrapper

---

Frontend/VIAProMa/Assets/MRTK/Core/Utilities.meta
Frontend/VIAProMa/Assets/Scenes/MainScene.unity
Frontend/VIAProMa/Assets/Scripts/DeepLinks/DeepLinkBootstrapper.cs
Frontend/VIAProMa/Assets/Scripts/DeepLinks/DeepLinkManager.cs
Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/InviteLinkGenerator.cs
Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinksHandler.cs
Frontend/VIAProMa/Assets/Scripts/DeepLinks/VIAProMaDeepLinks.md

Combined the previously added functions for complete basic invite deep link support.
Added documentation to functions and cleaned up code in general.
Added documentations describing how to use invite deep links as well as add other deep links.
closes #315

DeepLink | Combined functions, added documentation, general cleanup

---

Frontend/VIAProMa/Assets/Prefabs/UI/Menus/InviteLink Window.prefab
Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/InviteLinkMenu.cs

added a text that gives feedback when you use the invite link share buttons

forgot to push last commit

---

Frontend/VIAProMa/Assets/GuidedTour/Configuration/GuidedTour.json
Frontend/VIAProMa/Assets/GuidedTour/Scenes/GuidedTourScene.unity
Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourManager.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourUtils.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/AbstractTourTask.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTaskEventHandler.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTourTask.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTourTask.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/SimpleTourTask.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/UnlinkedTourTask.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/UnlinkedTourTask.cs.meta
Frontend/VIAProMa/Assets/Prefabs/Shelves/Resources/GuidedTour_IssueShelf.prefab

GuidedTour | Changes in logic of the GuidedTourManager

---

Frontend/VIAProMa/Assets/Prefabs/Managers.prefab
Frontend/VIAProMa/Assets/Scripts/Audio/AudioListener.cs
Frontend/VIAProMa/Assets/Scripts/Audio/AudioManager.cs
Frontend/VIAProMa/Assets/Scripts/Visualizations/BuildingProgressBar/BuildingProgressBarVisuals.cs
Frontend/VIAProMa/Assets/Scripts/Visualizations/Progress Bar/ProgressBarController.cs

Can be tested in the Test scenes respectively

Added sounds for ProgressBar and BuildingVisual

---

Frontend/VIAProMa/Assets/GuidedTour/Prefabs/Notification Widget Guided Tour.prefab
Frontend/VIAProMa/Assets/GuidedTour/Prefabs/Notification Widget Guided Tour.prefab.meta
Frontend/VIAProMa/Assets/GuidedTour/Scripts/NotoficationWidget.cs
Frontend/VIAProMa/Assets/GuidedTour/Scripts/NotoficationWidget.cs.meta

Merge Notification Widget into develop.

Created Notification Box #352

---

Frontend/VIAProMa/Assets/Scripts/DeepLinks/DeepLinkBootstrapper.cs
Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/ConfirmationWindow.cs
Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/InviteLinkMenu.cs

fixed joing be confirmation window, joining by link that starts app and roomwindow now closes when another room is joind via confirmation window

DeepLink | (hopefully) final fixes

---

Frontend/VIAProMa/Assets/Prefabs/Visualizations/BuildingProgress Bar/Resources/Building Progress Bar.prefab
Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/Progress Bar.prefab

Adds the missing references for the progress bar and the building progress bar
closes #289

Progressbar missing ref fix 

---

Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/ProjectPreferences.asset
Frontend/VIAProMa/Assets/Prefabs/Issue Cards/Card List View Item.prefab
Frontend/VIAProMa/Assets/Prefabs/Multiplayer/Resources/Avatar Networked.prefab
Frontend/VIAProMa/Assets/Prefabs/Shelves/Resources/IssueShelf.prefab
Frontend/VIAProMa/Assets/Prefabs/Visualizations/BuildingProgress Bar/Resources/Building Progress Bar.prefab
Frontend/VIAProMa/Assets/Prefabs/Visualizations/Competence Display/Resources/CompetenceDisplay.prefab
Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/Progress Bar.prefab
Frontend/VIAProMa/Assets/Scripts/IssueEditing/DeleteButtonOpener.cs
Frontend/VIAProMa/Assets/Scripts/IssueEditing/DeleteButtonOpener.cs.meta
Frontend/VIAProMa/Assets/Scripts/ScriptableObjects/Multiplayer/Resources/NetworkPrefabs.asset
Frontend/VIAProMa/Assets/Scripts/UI/ListView/Core/DataDisplay.cs

This branch fixed issue #417 s.t. the deletion button does not appear for Github issues anymore.

Fixed Issue #417

---

Frontend/VIAProMa/Assets/Tests/Visualizations/ListTaskCards.meta
Frontend/VIAProMa/Assets/Tests/Visualizations/ListTaskCards/ListTaskCardTestRunner.cs
Frontend/VIAProMa/Assets/Tests/Visualizations/ListTaskCards/ListTaskCardTestRunner.cs.meta
Frontend/VIAProMa/Assets/Tests/Visualizations/ListTaskCards/ListTaskCards.unity
Frontend/VIAProMa/Assets/Tests/Visualizations/ListTaskCards/ListTaskCards.unity.meta

- Adds a list task card test scene
- This test scene can be found under "Tests/Visualizations/ListTaskCards"

Adds a list task card test scene

---

Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Progress Bar Configuration Window.prefab
Frontend/VIAProMa/Assets/Scripts/Visualizations/Configuration Window Core/ConfigurationIssueListUI.cs

- Show a message if no task cards are assigned to a visualization is the task card list window is opened
- ![Screenshot 2022-06-27 164411](https://user-images.githubusercontent.com/11296360/175968464-8cfe9309-6f4b-4906-b301-7a15973a6e8c.png)

Add "is empty" message to task card list window

---

Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Competence Display Configuration Window.prefab
Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Issue List.meta
Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Issue List/Issue List Window.prefab
Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Issue List/Issue List Window.prefab.meta
Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Issue List/ShowVisualizationContent TextButton.prefab
Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Issue List/ShowVisualizationContent TextButton.prefab.meta
Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Kanban Column Configuration Window.prefab
Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Progress Bar Configuration Window.prefab
Frontend/VIAProMa/Assets/Scripts/Visualizations/CompetenceDisplay/CompetenceDisplayConfiguration.cs
Frontend/VIAProMa/Assets/Scripts/Visualizations/Kanban Board/KanbanBoardConfigurationWindow.cs

- Made Task Card List Compatible With All Visualizations
- Kanbis Board
- Competence Display

Made Task Card List Compatible With All Visualizations

---

Frontend/VIAProMa/Assets/Tests/DragAndDrop/Card With DandD.prefab
Frontend/VIAProMa/Assets/Tests/DragAndDrop/DragAndDrop.cs

A line indicates which visualizations currently overlap with the
issue to give the user more feedback on where he is about to add
the issue.
If only one visualization overlaps, the indicator on the issue is
enough.

Drag and Drop Implemented Overlap Indicator feature

---

Frontend/VIAProMa/Assets/Tests/DragAndDrop/DragAndDrop.cs

The issue card will only be considered for dropping when it is below
a certain speed. This way, accidental dropping while moving an issue
card is less likely

Drag and Drop Speed condition functionality fully implemented

---

Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Issue List/Issue List Window.prefab
Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Progress Bar Configuration Window.prefab
Frontend/VIAProMa/Assets/Scripts/Visualizations/Configuration Window Core/ConfigurationIssueListUI.cs

- Added XML comments
- Added Comments which can be see in the editor for the serialized fields

Added Documentation to Task Card List Implementation

---

Frontend/VIAProMa/Assets/Scripts/Shelf/Widgets/CopyMover.cs

updated copymover.cs to implement feature

cards now get removed from kanban board when dragging issue out

---

Frontend/VIAProMa/Assets/Scripts/DragAndDrop.cs

made variable public get for others see if issue is being destroyed

---

Backend/etc/launcher-configuration.ini
Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/Kanban Board Column.prefab
Frontend/VIAProMa/Assets/Scripts/IssueEditing/DeleteButton.cs
Frontend/VIAProMa/Assets/Scripts/IssueEditing/EditButton.cs
Frontend/VIAProMa/Assets/Scripts/Visualizations/CompetenceDisplay/UserScoreDisplay.cs
Frontend/VIAProMa/Assets/Scripts/Visualizations/TextLabel.cs

In an effort to clean up the proposed Pull Request #489, the issues that are worked on on the corresponding graph have been split up over multiple branches. This pull request contains the corresponding changes made to remove the delete button from issue cards when not in the shelf as well resolves the issue of the competence display creating an infinite plane in the background if the first and last name of a user is not given.

Resolved Issues #496 and #497

---

Frontend/VIAProMa/Assets/Prefabs/Visualizations/Diagrams/Axis Label.prefab
Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/CommitStatisticsVisualization.prefab

This pull-request fixes the errors that occurred when using the commit statistics visualization and made it unusable. Now the errors do not appear anymore and the commit statistics works as intended again.

Commit-Statistics Visualizations
